# Generated by Django 6.0 on 2025-12-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Namba ya Usajili')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Jina Kamili')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Namba ya Simu')),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
